name: Continuous Integration

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  continuous-integration:
    # We need to run on macos-latest since it's the only runner that supports nested
    # virtualization. The actual CI workflow will run on an archlinux VM that we spin up
    # using Vagrant. The reason behind this is that we need bleeding edge kernels to test
    # BPFContain, since it uses the latest eBPF features.
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: cache vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: show vagrant version
        run: vagrant --version

      - name: run vagrant up
        run: vagrant up

      - name: print uname
        run: vagrant ssh -c "uname -a"

      - name: build
        run: vagrant ssh -c "cargo build"

      - name: clippy lints
        run: vagrant ssh -c "cargo clippy -- -D warnings"

      - name: run rustfmt
        run: vagrant ssh -c "cargo fmt -- --check"

      - name: run tests
        run: vagrant ssh -c "cargo test"
